name = "Polyorder"
uuid = "c49c1de5-c720-4b6d-ae58-d24743c7f647"
authors = ["Yi-Xin Liu <lyx@fudan.edu.cn> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
